### ISSUE TITLE
Personalizable resources: give users more hints

### ISSUE THREAD

**Issue by elisabettai** [ITISFoundation/osparc-issues#1044]
Tested this scenario with Team Black: try to request a crazy amount of resources, e.g. 100Gb. The Service stays pending for 1h and then fails.

This might help the user experience:
1. The user has asked a crazy value by mistake: it would be nice to abort this request (i.e. being able to stop the service while it is pending) without having to close the study. See also this issue: #1045 
2. Can we somewhat estimate what is the biggest resource that be asked (based on our cluster configurations)? If yes, we can add constraints in the frontend.
3. Maybe: when user asks a crazy (tbd what is crazy) amount, there's a warning saying that it's possible that the request can't be fulfilled.

**Comment by elisabettai** [comment]
@sanderegg, just some points above for discussion, what do you think? 

The priority I guess also depends on who's going to have access to personalizable resources at the end. Only internal users? It might still be nice to give them some more hints. Also external ones?

**Comment by sanderegg** [comment]
@elisabettai 
I agree the current situation is not yet perfect.

There are a few things that are currently going on:
- Computational services **on local cluster**: currently if you ask for a crazy amount of resources it will fail right away with a message in the logs that you do not have the resources for this
- Computational services **on external clusters**: *we do not know what is available in the cluster, especially if it is autoscaling or so* - therefore the service that asks for too much will show "Waiting for resources" in the service since [https://github.com/ITISFoundation/osparc-simcore/pull/4549](https://github.com/ITISFoundation/osparc-simcore/pull/4549)
- Dynamic services: stays in pending for 1h and fails

**Comment by elisabettai** [comment]
Thanks @sanderegg for explaining. 
I think the most critical piece is to allow users to stop services while their pending. So I close this one in favour of #1045
