### ISSUE TITLE
Uploading file from inputs overview doesn't seem to make it available to the service directly. 

### ISSUE THREAD

**Issue by Konohana0608** [ITISFoundation/osparc-issues#1274]
**Long Story Short**
When I upload a file to my ti-pers service using the inputs menu, the service doesn't seem to find the files when trying to execute code that needs these files. When I disconnect and reconnect the file, the code execution works fine. 

**Expected Behavior**
The files should be available after the upload is finished

**Actual behaviour**
Files are not found by the code in the service unless reconnected.

**Steps to reproduce**
Please refer to the video:

https://github.com/ITISFoundation/osparc-issues/assets/61539759/6bd3187e-7124-4ab6-a24f-e281dc78c158

**Environment**
google chrome

**Additional context**
None

**Comment by jsaq007** [comment]
After looing at this with @odeimaiz we think this would be related to a bug @pcrespov may have come across last week. @pcrespov could that be right?

**Comment by pcrespov** [comment]
> After looing at this with @odeimaiz we think this would be related to a bug @pcrespov may have come across last week. @pcrespov could that be right?

@jsaq007 not sure what bug do you refer. Could you please give some more details?

**Comment by odeimaiz** [comment]
@pcrespov At the beginning we thought it was the case where the frontend is setting the output of the File Picker and the downstream nodes were not reacting to the change (the bug you found (and fixed?) last week). But it's not the case.

@Konohana0608, we believe that it's just a matter of waiting a bit longer so that your jLab downloads the file. I'm afraid your expected behaviour will not happen. When you upload a file through the Select File option, you are just uploading it to our storage, and then, the connected nodes, in your case jLab, needs to download it, which might take a while. What we can definitely do here is improve the UX by having a spinner icon next to the port spin while the file is being transferred to the jLab node.
