### ISSUE TITLE
Versioning Working Group

### ISSUE THREAD

**Issue by SCA-ZMT** [ITISFoundation/osparc-issues#1329]
Define a strategy for:
- marking "dev" vs. "LTS" (Long Term Support) versions of services such as Sim4Life, so that users know which versions will need to be upgraded, and which not
- aligning web and desktop release numbers
- make the service version and the "S4L version" be coherent and traceable

WG Lead: @mguidon

**Comment by mguidon** [comment]
## Conclusion

- All s4l-based services get identical version numbers
  - `sim4life`
  - `isolve`
  - `JupyterLab`
  - `python runner`
- For now, version numbers will be `8.0.0`, `8.0.1`, `8.0.2`. This requires the Desktop Versioning to be changed because the web will release more often
- The services will be named `sim4life 8.0` (next minor release `sim4life 8.2`) and user will be able to select patch versions
- We will buffer the latest official desktop version and the latest patch
- The Dashboard in the services tab will show all versions similar to the Tutorials in a list with headers: 8.0. 8.2, 9.0
- Since the service key will change from 8.0 to 8.2 we need to improve the updating mechanism in the frontend (first example will be moving from current `lite` to `lite 8.0`)
