### ISSUE TITLE
"progress" and "output" fields info lost

### ISSUE THREAD

**Issue by odeimaiz** [ITISFoundation/osparc-issues#139]
When closing a study, "progress" and "output" fields info in projects table is lost.

**Comment by sanderegg** [comment]
After some analysis the problem comes not from close but from saving the project.
Currently the frontend saves the project by sending a PUT to /projects/uuid endpoint.
this effectively replaces the project with whatever the frontend sends, which is correct. The frontend sends only a part of the project, where the outputs/progress are missing.

Basically, after running a pipeline. Moving a node around, triggers a PUT, which effectively removes the information already.
