### ISSUE TITLE
Wrong sharee permission - if shared with product group

### ISSUE THREAD

**Issue by elisabettai** [ITISFoundation/osparc-issues#1540]
Didn't we fix this bug?

![image](https://github.com/ITISFoundation/osparc-issues/assets/18575092/4e60d8b6-47b6-44ed-bf7c-d564e72300ab)

I am on sim4life.io and sim4life v3.2.27  is shared with Everybody as far as I can see

_Issue created from a [Mattermost message](https://mattermost.speag.com:443/_redirect/pl/8rt664bqytyouci5sfqcgpf97a) *by @elisabettai*._

**Comment by matusdrobuliak66** [comment]
## Found the issue
In the function `get_all_user_groups`
```python
async def get_all_user_groups(
    conn: SAConnection, user_id: UserID
) -> tuple[dict[str, Any], list[dict[str, Any]], dict[str, Any]]:
    """
    Returns the user primary group, standard groups and the all group
    """
    primary_group = {}
    user_groups = []
    all_group = {}

    query = (
        sa.select(groups, user_to_groups.c.access_rights)
        .select_from(
            user_to_groups.join(groups, user_to_groups.c.gid == groups.c.gid),
        )
        .where(user_to_groups.c.uid == user_id)
    )
    row: RowProxy
    async for row in conn.execute(query):
        if row.type == GroupType.EVERYONE:
            assert row.access_rights["read"]  # nosec
            all_group = convert_groups_db_to_schema(row)

        elif row.type == GroupType.PRIMARY:
            assert row.access_rights["read"]  # nosec
            primary_group = convert_groups_db_to_schema(row)

        else:
            assert row.type == GroupType.STANDARD  # nosec
            # only add if user has read access
            if row.access_rights["read"]:  # MD: <-- Why this if is here?
                user_groups.append(convert_groups_db_to_schema(row))

    return (primary_group, user_groups, all_group)
```
We are filtering out row.access_rights["read"]. The product group has it set to false, so the product group is excluded. This needs to be changed. However, I understand there is a reason it was added here: the frontend doesn't want to see the product groups. We need to start differentiating between organizations for the frontend and all other groups.

**Comment by matusdrobuliak66** [comment]
There was an issue with the filtering functionality related to user groups. Users who had access to a special product group (such as osparc, sim4life, or tip) were not being correctly displayed when filtering all user groups. This occurred because these special product groups were not part of any organization groups, which are also treated as groups in the backend.

As a result, when attempting to filter all user groups, the special product groups were missing from the results. This bug has now been fixed, ensuring that all relevant user groups, including the special product groups, are correctly included in the filtering process.
