### ISSUE TITLE
Option to request study owner to stop sharing

### ISSUE THREAD

**Issue by KZzizzle** [ITISFoundation/osparc-issues#310]
**Describe the user role**
As a Z43 user with whom someone else has shared a study

**Describe the goal**
Have an option (perhaps in the shared study options) to request study owner to stop sharing the study with me

**Describe the benefit**
my Dashboard is not spammed by people who share studies with me forever

**Additional context**
original contributor: Cosimo

**Comment by calys** [comment]
Counter proposal: improve/enhance the Dashboard so that studies that are shared with me can be easily ignored, hidden or made more prominent. An example I like is the way Google Photos or Google Drive works. Anyone can share photo albums or files with me, and I can see them in the "Shared with me" tab. For the interesting items, I can then click on "Import" (I think it's just an icon, actually...) to copy the item (or a link to it) into my own library. The "Shared with me" tab is then no more than a (searchable) staging area between "stuff I receive from other people" and "stuff I actually care about".

**Comment by elisabettai** [comment]
Also related to #935, might even be considered duplicate

**Comment by elisabettai** [comment]
I believe this can be closed now. We have:
1. option to filter my studies/studies shared with me in the Dashboard (https://github.com/ITISFoundation/osparc-simcore/pull/4050)
2. Button to "Leave a Study".

We cannot get feedback from @calys, but I guess this issue is now obsolete. fyi @odeimaiz
