### ISSUE TITLE
Older study overwrites more recent one

### ISSUE THREAD

**Issue by odeimaiz** [ITISFoundation/osparc-issues#435]
1. User A creates a study and shares it with B.
2. User B opens it and doesn't close it but looses connection and after a while the study gets unlocked.
3. User A opens it and does some work. Finishes and closes the study.
4. User B reconnects and the opened, but empty, study is still there. User B ends up overwriting all the progress with the empty study.

@newton1985 @esraneufeld

**Comment by pcrespov** [comment]
*@pcrespov attached a* [message](https://mattermost.speag.com:443/_redirect/pl/kr3yrx7yofdi5epqzbukg3u4zr) *from `@newton`*

Last night I created new content in a study, and then closed it and went to sleep

**Comment by sanderegg** [comment]
experiment done here with @odeimaiz:

1. user 1 connects to osparc on laptop
2. user 1 opens a study A on laptop
3. user 1 connects on computer B (study A is shown as locked by user 1)
4. laptop is disconnected 
5. remove alive key in redis corresponding to the user on the laptop or wait 15 minutes
6. garbage collector correctly closes the study after the GC interval goes through
7. first issue: computer B does not receive the event that the study is unlocked. user 1 must refresh the screen, now ok.
8. user 1 on computer B goes in the study and changes it, then closes the study
9. laptop is connected again, the study is still open in the last state
10. the laptop saves the study, overwriting the changes done from computer B
11. the user on computer B does not see a Lock on study A when laptop re-connected.


Several problems and possible solutions:
- websocket events are not transmitted to computer B when the study is closed by the GC?
- websocket events not transmitted when the laptop re-connects (because it did not re-open the study), actually the laptop should be kicked out of the study right away
- saving the study when it was not opened before should be disallowed

**Comment by KZzizzle** [comment]
@sanderegg is this still an issue with the above merges?

**Comment by sanderegg** [comment]
@KZzizzle I think we can close that one

**Comment by KZzizzle** [comment]
cool, let's close!
