### ISSUE TITLE
Semcad icon does not show

### ISSUE THREAD

**Issue by mguidon** [ITISFoundation/osparc-issues#486]
## Long story short
Very sad...
![image](https://user-images.githubusercontent.com/33161876/123062577-f16bc500-d40c-11eb-9660-a8ca047f01dc.png)

Are there some rules to follow when designing beautiful thumbnails?

https://imgur.com/ymLzzsG

**Comment by mguidon** [comment]
Update. Since yesterday I am in possession of a beautiful holiday picture from a coworker. I think I will try that one...

@pcrespov Would you agree?

**Comment by odeimaiz** [comment]
I wouldn't play dirty games with that coworker if he is the master of paint....

Closing case because the link was not an image, but a website:
https://i.imgur.com/ymLzzsG.gif

After pointing to the correct url:
![image](https://user-images.githubusercontent.com/33152403/123660433-f1682c80-d833-11eb-9ab0-9dd5440ca1df.png)

**Comment by mguidon** [comment]
Aha, that explains a lot...
