### ISSUE TITLE
AWS, S-D22, Y3M5,1-12

### ISSUE THREAD

**Issue by KZzizzle** [ITISFoundation/osparc-issues#5]
the deployment version of o2S2PARC is transferred to AWS
- [x] transfer deployment version of o2S2PARC to AWS 
- [x] reserve for Amazon usage (strongly dependent on decision for 3rd party platform use)

**Comment by odeimaiz** [comment]
Goal for Mythos:
- [ ] Mail server
- [ ] Security review
- [ ] Staging platform

**Comment by Surfict** [comment]
We have now a fully working aws OSPARC platform on AWS.

The infrastructure is almost the same that was we have in the current production, in terms of resources and organization.

The next step is to improve this infrastructure to obtain a fully high-available infrastructure in order to prevent any breakdown.

State of progress: 80 %

**Comment by KZzizzle** [comment]
Now available at https://simcore.io/

**Comment by Surfict** [comment]
Schema of the production infrastructure :

![AWS schema.PNG](https://images.zenhubusercontent.com/5dc15c67be940c0001fec9fd/4818f529-b3c0-4d01-9fe2-55acb33d5a7f)
