### ISSUE TITLE
Bind service theme to osparc theme

### ISSUE THREAD

**Issue by odeimaiz** [ITISFoundation/osparc-issues#543]
@rediani requests:
Is it possible to link jupyter notebook Dark/Light theme setting to the general Dark/Light mode setting of Osparc? At the moment whenever i open a notebook, it's set by default to white.

**Comment by pcrespov** [comment]
@GitHK I guess we can set this via env vars, or perhaps passing a config in the workdir right? Can we have a demo in the jupyter-math as example?

**Comment by GitHK** [comment]
@odeimaiz the selected theme style dark/light is only saved in the frontend, is this correct?

@pcrespov I would like to have it stored in the database, because it will make life easier. Afterwards it is simple to add an env var to all new dynamic services.

I can already add support for jupyter-math 2+

**Comment by pcrespov** [comment]
> @pcrespov I would like to have it stored in the database, because it will make life easier. Afterwards it is simple to add an env 
var to all new dynamic services.

what about adding instead the ``config`` capabilites in docker-compose that we spoke this morning. This we we can pass configurations to the application

**Comment by elisabettai** [comment]
Not resolving for now.
