### ISSUE TITLE
Duplicate Study Does not work

### ISSUE THREAD

**Issue by AntoninoMarioC** [ITISFoundation/osparc-issues#715]
**Long Story Short**
The duplication of a study doesn't work

**Expected Behavior**
A duplicate should be created

**Actual behaviour**
A message tells that a duplicate is being created while it doesn't

**Environment**
https://osparc.speag.com/

**Comments**
The functionalities for saving and cloning and restore studies should have larger priority than anything else.

**Comment by elisabettai** [comment]
Hi @AntoninoMarioC, could you give the name/uuid of the study you're trying to copy? Does it contain a lot of data (>30GB)? In the case of studies with lot of data, we're still refining the duplicate feature (@sanderegg was working on it).

btw, I've just tried copying a small study and that work.

**Comment by sanderegg** [comment]
@elisabettai , @AntoninoMarioC :
together with @AntoninoMarioC I found that the project had a reference to a file that was not in the S3 backend (probably due to some cleaning done). the duplication finally worked.
The lack of feedback is beging tackled in the current sprint and is documented in issue [https://github.com/ITISFoundation/osparc-issues/issues/558](https://github.com/ITISFoundation/osparc-issues/issues/558)

**Comment by AntoninoMarioC** [comment]
Manually solved by @sanderegg. Closing for the moment.
