### ISSUE TITLE
Convert published studies in osparc.io to latest cMIS

### ISSUE THREAD

**Issue by pcrespov** [ITISFoundation/osparc-issues#769]
- review published studies in osparc.io
- check format of current data in pennsieve
- check definition of latest cMIS and document on our side
- update to latest 
    - see example provided by MAP-core
    - create script
    - how feasible is to add it in osparc in the export option ?

**Comment by elisabettai** [comment]
Thanks @pcrespov for creating this issue. 

It looks like the updates I did to three our of datasets (4, 7, 78) as part of the work with AG from MAP-Core are not reflected on the published datasets on the Portal (specifically the new files I've added to conform with the guidelines provided by AG regarding the curation of computational datasets). I've asked AG if he has an idea of why that doesn't work.

As soon as I understand how the updated get reviewed/published, I'll proceed with updating all our datasets (and doing so with a script, if possible, most of the work is filling in an Excel file with metadata related to the study).

For cMIS, we need to finalize the feedback we received from the standardization committee with EN. I'll try to revive this topic soon. We also have #673 (which is the final product on the Portal, due by May 2023)

**Comment by elisabettai** [comment]
Small step forward: our datasets ([4](https://sparc.science/datasets/4?type=simulation&datasetDetailsTab=abstract), [17](https://sparc.science/datasets/17?type=simulation&datasetDetailsTab=abstract), [78](https://sparc.science/datasets/78?type=simulation)) are now updated on the Portal (they have the same metadata as the one shared by MAP-Core).

There's still an ongoing problem with MAP and K-Core, because MAP cannot fetch them with their API (they don't seem to be re-indexed?). Discussion happening on Slack.

For updating all our published datasets: I'd propose to wait for the finalization of cMIS. EN resumed working on it on Jan 9, and we should have an initial proposal soon.

We'll also probably need to re-enable the osparc export option.

**Comment by elisabettai** [comment]
Finally we got one of our datasets on the SPARC Portal that can be run in oSPARC as well with the Simulation Viewer from MAP-Core! It is dataset [308]( https://sparc.science/datasets/308?type=simulation). This will replace the previous version of Kember on the Portal (dataset [78](https://sparc.science/datasets/78?type=simulation)).

To get it published, from our side, we needed to update the metadata (mainly the `dataset_description.xlsx` file to [SDS V2](https://github.com/SciCrunch/sparc-curation/tree/dataset-template-2.0.0/resources/DatasetTemplate) via Pennsieve.

We're now working on;
- getting the two other published (they have been already submitted to K-Core for approval on March 29th.
- see how we can remove/deprecate old datasets, e.g. dataset [78](https://sparc.science/datasets/78?type=simulation).

**Comment by elisabettai** [comment]
Datasets 4, 17 and 78 have been updated with the latest versions of the SDS and now show the button to launch the oSPARC study of MAP-Core simulation viewer. The three new datasets are here:
- https://sparc.science/datasets/308?type=simulation
- https://sparc.science/datasets/318?type=simulation
- https://sparc.science/datasets/320?type=simulation

The only remaining "issue" it that we need to remove dataset 4 and 17 from the Portal, but for that we have this [wrike ticket](https://www.wrike.com/open.htm?id=1129650785).

I am closing, as this unblocks the work with MAP-Core. 

Ideally, we should also update our old datasets to the latest SDS at some point.
