### ISSUE TITLE
New start/stop dy-services: if node is deleted it should be removed from the count of running dy-services

### ISSUE THREAD

**Issue by elisabettai** [ITISFoundation/osparc-issues#782]
**Expected Behavior**
If 5 dynamic services are started (=the limit is reached), deleting a running dy-service should bring the count of running dy-service to 4.

**Actual behaviour**
After deleting a running node, the user still get the pop-up saying the max. number or running services is reached.

**Steps to reproduce**
Start 5 dy-services, delete one, try to add another one

**Comment by sanderegg** [comment]
@elisabettai 
The computation for the number of running services is done each time dynamically.
I think this problem is due to the fact that the node instantly disappears from the GUI but is in fact removed in the backend and that takes some time (i.e. removing the docker containers of the service, the dy-proxy and dy-sidecar respectively). 
Did you try like a minute later?
We should maybe think on how to give a better feedback.

**Comment by elisabettai** [comment]
@sanderegg, thanks for the feedback. I see what happens then. 
I just tried now with services that don't have data inside and I didn't see the problem anymore. Only once I had to re-try and worked after few seconds.
