### ISSUE TITLE
working group: publishing explorable data analyses in jupyterlab

### ISSUE THREAD

**Issue by esraneufeld** [ITISFoundation/osparc-issues#793]
we advertise and got requests to publish data in explorable forms. e.g., as supplement to publications.
examples could include a
- jupyterlab preconfigured to generate the graphs in a paper. at the same time, visitors should be able to play with the data, plot things differently, perform analyses...
access to this would be open to anonymous users.
- when niels recently wanted something similar done, the team strongly advised against for security reasons. as this is an important, repeated use-case that we also advertise often, we would like the team to think about how the security concerns could be overcome.

**Comment by esraneufeld** [comment]
we advertise and got requests to publish data in explorable forms. e.g., as supplement to publications.
examples could include a jupyterlab preconfigured to generate the graphs in a paper. at the same time, visitors should be able to play with the data, plot things differently, perform analyses...
access to this would be open to anonymous users.
when niels recently wanted something similar done, the team strongly advised against for security reasons. as this is an important, repeated use-case that we also advertise often, we would like the team to think about how the security concerns could be overcome.

**Comment by elisabettai** [comment]
We had an initial discussion on Jan 5 (@Surfict, @GitHK, @mrnicegyu11, @elisabettai). 

The team still strongly advice against opening Jupyterlab (i.e. services with a terminal) to anonymous users. The reason is that the following scenarios can happen:

1. A user can hack the machines (e.g. remove platform data?)
2. Using all the resources available for an unlimited amount of time (and prevent other users from using the platform)
3. Doing illegal actions (e.g. distributing illegal content)
4. Send spam

This scenarios have low probability, but high impact (AWS can ban us/ban the NIH strides?). Plus, with anonymous access, we have no way to track who's abusing the platform. The above scenarios can happen with registered users as well, but at least we know who's abusing the platform and can ban users.

Possible solutions for the above points:
1. Not solvable, a malicious user can always find a way to hack
2. Limiting session times (for anonymous users)
3 and 4: disable Internet access

Conclusion: it is preferred that only registered users can use jupyterlab (and other services that have a terminal). If this is an acceptable solution, we also brainstormed some ideas to make the registration process easier.
