### ISSUE TITLE
Failing nodes and study copying

### ISSUE THREAD

**Issue by elisabettai** [ITISFoundation/osparc-issues#809]
I'm experiencing some failing nodes on osparc.io in this study:
89950306-7d39-11ed-9ab3-02420a0b122b

_Issue created from a [Mattermost message](https://mattermost.speag.com:443/_redirect/pl/jgqh7ufcujfeigj6uejanifzco) *by `@newton`*._

**Comment by sanderegg** [comment]
@newton1985 
this problem is linked to https://github.com/ITISFoundation/osparc-simcore/pull/3462

Since the S3 object names are now composed using subfolders, the copy mechanism in storage is not working as it should and changes the path of the outputs to the old path. Thus, when the node starts, it is unable to pull the outputs in the service and fails.

**Comment by sanderegg** [comment]
workaround for now is to use ```publish without data```
