### ISSUE TITLE
Service taking long to load

### ISSUE THREAD

**Issue by elisabettai** [ITISFoundation/osparc-issues#939]
A study on dalco prod is taking long to open, jupyter-smashs for example: 85aa5e58-39dd-58d4-8620-888cabd

_Issue created from a [Mattermost message](https://mattermost.speag.com:443/_redirect/pl/ps5szbyzti8w78h7j8jrq947oo) *by `@benllochgarcia`*._

@pcrespov, @GitHK  please close when is done and refer to existing issues (if it's known) or put more info here.

**Comment by GitHK** [comment]
Dalco deployment was no longer able to run any services. All resources were used by pending services.
Deployment was cleaned up. There is a known issue where the `can_save` is only provided when shutting down, but it must be provided also when the services is started, since this information is known in advance.
